import '@shopify/shopify-api/adapters/web-api';
import { shopifyApi, ApiVersion, LogSeverity } from '@shopify/shopify-api';

export const shopify = shopifyApi({
  apiKey: process.env.SHOPIFY_API_KEY || 'test_api_key',
  apiSecretKey: process.env.SHOPIFY_API_SECRET || 'test_api_secret',
  scopes: process.env.SHOPIFY_SCOPES?.split(',') || [
    'read_analytics', 'read_apps',
    'write_assigned_fulfillment_orders', 'read_assigned_fulfillment_orders',
    'read_customer_events',
    'write_customers', 'read_customers',
    'write_discounts', 'read_discounts',
    'write_draft_orders', 'read_draft_orders',
    'write_files', 'read_files',
    'write_fulfillments', 'read_fulfillments',
    'write_gift_cards', 'read_gift_cards',
    'write_inventory', 'read_inventory',
    'write_locations', 'read_locations',
    'write_marketing_events', 'read_marketing_events',
    'write_metaobject_definitions', 'read_metaobject_definitions',
    'write_metaobjects', 'read_metaobjects',
    'write_order_edits', 'read_order_edits',
    'write_orders', 'read_orders',
    'write_payment_terms', 'read_payment_terms',
    'write_products', 'read_products',
    'read_publications', 'write_publications',
    'write_reports', 'read_reports',
    'write_returns', 'read_returns',
    'write_shipping', 'read_shipping',
    'write_locales', 'read_locales',
    'write_markets', 'read_markets',
    'write_themes', 'read_themes',
    'write_translations', 'read_translations',
    'write_content', 'read_content',
    'write_companies', 'read_companies',
  ],
  hostName: process.env.SHOPIFY_APP_URL?.replace(/https:\/\//, '') || 'localhost:3000',
  isEmbeddedApp: true,
  apiVersion: ApiVersion.July25,
  logger: {
    level: LogSeverity.Info,
  },
});
